apiVersion: v1
kind: Pod
metadata:
 name: sfr-pod-deploy-autocomplete-ALIAS
 namespace: sfr-ns-ALIAS
 labels:
   app_name: autocomplete-ALIAS
spec:
  restartPolicy: OnFailure
  volumes:
    - name: sfr-home-pv-ALIAS
      persistentVolumeClaim:
        claimName: sfr-home-pvc-ALIAS
    - name: sfr-share-pv-ALIAS
      persistentVolumeClaim:
        claimName: sfr-share-pvc-ALIAS
  containers:
    - name: pytorch-allennlp-test
      image: "deepjavalibrary/djl-serving:0.24.0-fastertransformer"
      command: ["/bin/bash","-c","sleep infinity"]
      resources:
        limits:
          nvidia.com/gpu: 2
          cpu: "23"
          memory: 150G
      volumeMounts:
        - name: sfr-home-pv-ALIAS
          mountPath: "/export/home"
        - name: sfr-share-pv-ALIAS
          mountPath: "/export/share"
      env:
        - name: AWS_DEFAULT_REGION
          value: us-west-2
  nodeSelector:
    cloud.google.com/gke-accelerator: nvidia-tesla-a100        
  tolerations:
  - key: "gpu_num"
    operator: "Equal"
    value: "2"
    effect: "NoSchedule"
